plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
email: contact@shyaman.me
cv: https://drive.google.com/file/d/17XYCQ3qN6mOXZ4e3YI1cslJaNHPc0Tzs/view?usp=sharing
linkedin: https://www.linkedin.com/in/shyamanj
scholar: https://scholar.google.com/citations?user=LJn7bbAAAAAJ&hl=en
orcid: https://orcid.org/0000-0003-0522-3353
flickr: https://www.flickr.com/photos/shyaman321
github: https://github.com/shyaman/
twitter_url: https://twitter.com/shyaman_madhawa
twitter:
  username: shyaman_madhawa
  card: summary
youtube: https://www.youtube.com/channel/UChoPlHOdGXodB_2D2yNOf2w
bio: I'm a passionate data science enthusiast with a keen interest in
  bioinformatics and computational biology. Beyond the world of data, I find joy
  in exploring new places and capturing precious moments with my loved ones.
description: >-
  Shyaman Jayasundara is a PhD student in Computer Science at Purdue University,
  working on computational biology and bioinformatics.
logo: /assets/img/apple-touch-icon.png
repository: shyaman/shyaman.github.io
url: https://www.shyaman.me
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/IMG_5006-Edit.jpg
  - scope:
      path: admin/**
    values:
      sitemap: false
timezone: Asia/Colombo
currentTitle: "PhD Student (Computer Science) | B.Sc. Eng (Hons) | Ex: Merck"
